#
# (c) Copyright IBM Corp. 2025
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM docker.io/library/oso-builder:latest as builder

COPY pyproject.toml uv.lock ./
COPY src src
RUN uv pip install --python=/opt/oso/venv .

FROM docker.io/library/oso-runtime:latest as fireblocks-runtime
COPY --from=builder --chown=1001:0 /opt/oso /opt/oso
